Featur/survey
GaitWise/GaitWise pull request #2
Opened 2024-09-27 10:59 UTC by HiSoo38

survey 화면에 gender 선택하는 화면 만들었습니다

2024-09-27 11:57 UTC, jiseungmin reviewed
수정 부탁드려요.

2024-09-27 11:57 UTC, jiseungmin commented on app/survey/gender.js
> +      </View>
피그마 보시면 위 상단바는 거의 고정으로 들어가기 때문에
다른 설문조사 페이지마다 상단바 UI 코드를 계속 써야하니깐
이런식으로 코드 작성한 특별한 이유가 없으면 _layout.js를 이용해서
스택 네비게이션을 써보는게 좋을 거 같아요.

2024-09-27 11:57 UTC, jiseungmin commented on app/survey/_layout.js
>  export default function HomeLayout() {
HomeLayout -> SurveyLayout으로 수정

2024-09-27 11:57 UTC, jiseungmin commented on app/survey/gender.js
> +  },
코드 가독성이나 코드 길이를 고려해서 중복된 스타일 속성은 
하나만 남겨둬서 코드에 사용하면 좋을 거 같아요.

2024-09-27 12:33 UTC, HiSoo38 commented on app/survey/gender.js
> +      </View>
19번째 줄에 onPress={() => navigation.navigate("login") 이 코드가 들어가야하는데 git에 올리고 수정한거라 안들어갔네욥.. 이 코드가 들어가면 이전화면으로 back할 수 있게되는데 layout에 넣으면 이전화면으로 돌아가는게 아니라 login화면으로 돌아가게되서 layout에 안넣는게 좋을 것 같습니다

2024-10-02 16:33 UTC, takaaaaaan reviewed
memo test

2024-10-02 16:33 UTC, takaaaaaan commented on app/survey/_layout.js
> +});
✅ stayled-component 사용해주세요

2024-10-02 16:33 UTC, takaaaaaan commented on app/survey/login.js
> +      <ScrollView>
✅  Srollview 사용 안한다면 뺴주세요

2024-10-02 16:33 UTC, takaaaaaan commented on app/survey/login.js
> +  const [pw2, onChangepw2] = useState("");
✅  입력 테스트 해봤나요?

2024-10-02 16:33 UTC, takaaaaaan commented on app/survey/_layout.js
>  });
✅ SC 사용해주세요

2024-10-02 16:35 UTC, takaaaaaan reviewed
asdfsadf

2024-10-02 16:35 UTC, takaaaaaan commented on app/survey/_layout.js
> +const styles = StyleSheet.create({
zxvzxcvzx

2024-10-03 03:37 UTC, takaaaaaan requested changes

2024-10-03 03:37 UTC, takaaaaaan commented on app/survey/_layout.js
> +
✅ Styled-component 사용해주세요

2024-10-03 03:40 UTC, takaaaaaan commented on app/survey/_layout.js
> +
이 부분은 끝나면 merge해도 될거 같아요 일단

2024-10-08 00:42 UTC, HiSoo38 commented on app/survey/_layout.js
> +
_layout 완료 했습니다.

2024-10-08 00:53 UTC, takaaaaaan reviewed
수정 사항 올린거 하고 코멘트 올려주세요

2024-10-08 00:53 UTC, takaaaaaan commented on app/survey/age.js
> +export default Age;
✅ css 위에 올려주세요

2024-10-08 00:53 UTC, takaaaaaan commented on app/survey/login.js
>  import { TouchableOpacity, TextInput, ScrollView } from "react-native";
✅ 사용 안하는건 뺴고 올려주세요

2024-10-10 00:45 UTC, HiSoo38 commented on app/survey/login.js
>  import { TouchableOpacity, TextInput, ScrollView } from "react-native";
완료했습니다.

2024-10-10 00:45 UTC, HiSoo38 commented on app/survey/age.js
> +export default Age;
완료했습니다.

2024-11-04 10:36 UTC, takaaaaaan reviewed
전체적으로 주석 정리 한번해주세요

2024-11-04 10:36 UTC, takaaaaaan commented on app/survey/grade.js
> +import { COLORS, icons } from "../../constants";
@ 사용해주세요

2024-11-04 10:36 UTC, takaaaaaan commented on app/survey/height.js
> +import { COLORS } from "../../constants";
@ 사용해주세요

2024-11-04 10:36 UTC, takaaaaaan commented on app/survey/login.js
> +  const { firstName, lastName, job, email, pw, pw2 } = inputs;
pw,pw2 이름 수정 필요함
너무 단순함

2024-11-04 10:36 UTC, takaaaaaan commented on app/survey/data.js
> +import { icons } from '../../constants'; // 아이콘을 가져옵니다.
@로 바꿔줘요

2024-11-04 10:36 UTC, takaaaaaan commented on app/survey/grade.js
> +import Main from "../../components/common/main"; // 고정된 Grade 컴포넌트
@로 바꿔줘요

2024-11-04 10:36 UTC, takaaaaaan commented on app/survey/grade.js
> +  const [currentPageId, setCurrentPageId] = useState("grade"); // 초기 페이지 ID는 'grade'
초기는 나중에 수정 필요 API 완성하면 이 부분도 동적으로 초기 페이지 설정 되도록 해야함

2024-11-04 10:36 UTC, takaaaaaan commented on components/common/main.js
> +import { pagesData } from "../../app/survey/data";
@로 바꿔고 그리고 결로 확인 필요함 결로가 이상해요

2024-11-04 10:36 UTC, takaaaaaan commented on components/common/main.js
> +      navigation.navigate('age'); // 'NextScreen'은 이동할 화면의 이름
이거 push로 다 수정 필요함

2024-11-04 12:03 UTC, HiSoo38 commented on app/survey/login.js
> +  const { firstName, lastName, job, email, pw, pw2 } = inputs;
완료

2024-11-04 14:36 UTC, merged